---
apiVersion: v1
kind: ConfigMap
metadata:
  name: casc-config
data:
  casc.yaml: |
    credentials:
      system:
        domainCredentials:
        - credentials:
          - gitHubApp:
              appID: "${GITHUB_APP_ID}"
              description: "Local Kind cluster GitHUb org integration"
              id: "${CREDENTIALS_ID}"
              privateKey: "${GITHUB_ORG_PRIVATE_KEY}"
    jenkins:
      authorizationStrategy:
        loggedInUsersCanDoAnything:
          allowAnonymousRead: false
      securityRealm:
        local:
          allowsSignup: false
          users:
          - id: ${JENKINS_ADMIN_USERNAME}
            description: Base admin user
            password: ${JENKINS_ADMIN_PASSWORD}
    unclassified:
      location:
        url: "${JENKINS_URL}"
      gitHubConfiguration:
        apiRateLimitChecker: ThrottleForNormalize
      gitHubPluginConfig:
        hookUrl: "${JENKINS_URL}github-webhook/"
      globalLibraries:
        libraries:
        - defaultVersion: "${DEFAULT_GLOBAL_LIBRARIES_VERSION}"
          implicit: true
          name: "${GLOBAL_LIBRARIES_REPO_OWNER}"
          retriever:
            modernSCM:
              scm:
                github:
                  configuredByUrl: true
                  credentialsId: "${CREDENTIALS_ID}"
                  repoOwner: "${GLOBAL_LIBRARIES_REPO_OWNER}"
                  repository: "${GLOBAL_LIBRARIES_REPO_NAME}"
                  repositoryUrl: "${GLOBAL_LIBRARIES_REPO_URL}"
                  traits:
                  - gitHubBranchDiscovery:
                      strategyId: 1
                  - gitHubPullRequestDiscovery:
                      strategyId: 1
                  - gitHubForkDiscovery:
                      strategyId: 1
                      trust: "gitHubTrustPermissions"
---