apiVersion: v1
kind: ConfigMap
metadata:
  name: casc-config
data:
  casc.yaml: |
    credentials:
    system:
      domainCredentials:
      - credentials:
        - gitHubApp:
            appID: "99470"
            description: "Local Kind cluster GitHUb org integration"
            id: "Jenkins-KindLocal"
            privateKey: "${GITHUB_ORG_PRIVATE_KEY}"
    jenkins:
      authorizationStrategy:
        loggedInUsersCanDoAnything:
          allowAnonymousRead: false
      securityRealm:
        local:
          allowsSignup: false
          users:
          - id: ${JENKINS_ADMIN_USERNAME}
            description: Base admin user
            password: ${JENKINS_ADMIN_PASSWORD}
    unclassified:
      location:
        url: http://kind.local/
      gitHubConfiguration:
        apiRateLimitChecker: ThrottleForNormalize
      gitHubPluginConfig:
        hookUrl: "http://kind.local/github-webhook/"
