kind: Service
apiVersion: v1
metadata:
  name: k8s-api-healthcheck
spec:
  selector:
    app: k8s-api-healthcheck
  ports:
  - targetPort: 8080
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-api-healthcheck
  labels:
    app: k8s-api-healthcheck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-api-healthcheck
  template:
    metadata:
      labels:
        app: k8s-api-healthcheck
    spec:
      containers:
      - name: application
        image: norbega/k8s-api-healthcheck:v0.1.6
        resources:
          requests:
            cpu: 0.1
            memory: 64Mi
          limits:
            cpu: 0.1
            memory: 64Mi
        ports:
        - containerPort: 8080
